# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestListView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestListView
  pod 'Base64', '~> 1.1.2'
  pod 'Alamofire', '~> 4.0.1'
  pod 'Kingfisher', '~> 3.1.4'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'KDCycleBannerView', '~> 1.1.1'
  pod 'MYBlurIntroductionView', '~> 1.0.3'
  pod 'NJKWebViewProgress', '~> 0.2.3'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'PureLayout', '~> 3.0.2'
  pod 'Toast', '~> 3.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'RxSwift', '~> 3.0.0-rc.1'
  pod 'RxCocoa', '~> 3.0.0-rc.1'
  pod 'RxDataSources', '~> 1.0.0-rc.2'
end
